package cryptox

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"github.com/pkg/errors"
	"io"
	"strings"
)

type Aes struct {
	key  string
	safe bool
}

const defaultAesKey = "www.jaime.com.cn"
const aesGCMVersionPrefix = "gcm:"

type Option func(*Aes)

func WithSafe(safe bool) Option {
	return func(a *Aes) {
		a.safe = safe
	}
}

func WithKey(key string) Option {
	return func(a *Aes) {
		a.key = key
	}
}

// NewAes 创建aes加密
func NewAes(opts ...Option) *Aes {
	a := &Aes{
		key:  defaultAesKey,
		safe: false,
	}
	for _, opt := range opts {
		opt(a)
	}
	return a
}

func DefaultAes() *Aes {
	return NewAes()
}

// Encrypt 加密
func (a *Aes) Encrypt(plaintext string) (string, error) {
	if a.safe {
		return a.SafeEncrypt(plaintext)
	}
	return a.EncryptLegacy(plaintext)
}

// EncryptLegacy 加密
// 算法是 AES-CBC
// IV 是固定的，从 key 前 16 字节截出来
// 填充是 ZeroPadding
// 输出是：base64(ciphertext)
// 同一个 key、同一个明文，输出通常固定不变
func (a *Aes) EncryptLegacy(plaintext string) (string, error) {
	keyBytes, err := a.keyBytes()
	if err != nil {
		return "", err
	}
	block, err := aes.NewCipher(keyBytes)
	if err != nil {
		return "", err
	}
	paddedData := a.zeroPadding([]byte(plaintext), aes.BlockSize)
	iv := keyBytes[:aes.BlockSize]
	mode := cipher.NewCBCEncrypter(block, iv)
	ciphertext := make([]byte, len(paddedData))
	mode.CryptBlocks(ciphertext, paddedData)
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

// SafeEncrypt 安全加密
// 算法：AES-GCM
// 每次都会生成随机 nonce
// 自带完整性校验，密文被改动会解密失败
// 输出是："gcm:" + base64(nonce + ciphertext + tag)
// 同一个 key、同一个明文，每次输出都会不一样，因为 nonce 是随机的
func (a *Aes) SafeEncrypt(plaintext string) (string, error) {
	keyBytes, err := a.keyBytes()
	if err != nil {
		return "", err
	}

	block, err := aes.NewCipher(keyBytes)
	if err != nil {
		return "", err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err = io.ReadFull(rand.Reader, nonce); err != nil {
		return "", errors.Wrap(err, "aes.SafeEncrypt: generate nonce failed")
	}
	ciphertext := gcm.Seal(nil, nonce, []byte(plaintext), nil)
	payload := append(nonce, ciphertext...)
	return aesGCMVersionPrefix + base64.StdEncoding.EncodeToString(payload), nil
}

func (a *Aes) keyBytes() ([]byte, error) {
	if a.key == "" {
		a.key = defaultAesKey
	}
	keyBytes := []byte(a.key)
	keyLen := len(keyBytes)
	if keyLen != 16 && keyLen != 24 && keyLen != 32 {
		return nil, errors.New("aes.keyBytes: key length must be 16, 24, or 32 bytes")
	}
	return keyBytes, nil
}

// ZeroPadding is kept for legacy CBC compatibility only.
func (a *Aes) zeroPadding(data []byte, blockSize int) []byte {
	padding := blockSize - len(data)%blockSize
	if padding == 0 {
		padding = blockSize
	}
	padText := make([]byte, padding)
	return append(data, padText...)
}

// zeroUnPadding is kept for legacy CBC compatibility only.
func (a *Aes) zeroUnPadding(data []byte) []byte {
	length := len(data)
	if length == 0 {
		return data
	}
	for i := length - 1; i >= 0; i-- {
		if data[i] != 0 {
			return data[:i+1]
		}
	}
	return []byte{}
}

func (a *Aes) DecryptLegacy(content string) ([]byte, error) {
	keyBytes, err := a.keyBytes()
	if err != nil {
		return nil, err
	}

	ciphertext, err := base64.StdEncoding.DecodeString(content)
	if err != nil {
		return nil, err
	}
	if len(ciphertext)%aes.BlockSize != 0 {
		return nil, errors.New("ciphertext length is not a multiple of the AES block size")
	}

	block, err := aes.NewCipher(keyBytes)
	if err != nil {
		return nil, err
	}

	iv := keyBytes[:aes.BlockSize]
	mode := cipher.NewCBCDecrypter(block, iv)
	plaintext := make([]byte, len(ciphertext))
	mode.CryptBlocks(plaintext, ciphertext)
	return a.zeroUnPadding(plaintext), nil
}

// SafeDecrypt decrypts the AES-GCM payload generated by EncryptV2.
func (a *Aes) SafeDecrypt(content string) ([]byte, error) {
	keyBytes, err := a.keyBytes()
	if err != nil {
		return nil, err
	}

	payloadText := strings.TrimPrefix(content, aesGCMVersionPrefix)
	payload, err := base64.StdEncoding.DecodeString(payloadText)
	if err != nil {
		return nil, err
	}

	block, err := aes.NewCipher(keyBytes)
	if err != nil {
		return nil, err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}

	nonceSize := gcm.NonceSize()
	if len(payload) < nonceSize {
		return nil, fmt.Errorf("aes.SafeDecrypt: invalid GCM payload length: %d", len(payload))
	}

	nonce, ciphertext := payload[:nonceSize], payload[nonceSize:]
	plaintext, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, errors.Wrap(err, "aes.SafeDecrypt: decrypt GCM payload")
	}
	return plaintext, nil
}

// Decrypt supports both the V2 GCM format and the legacy CBC format.
func (a *Aes) Decrypt(content string) ([]byte, error) {
	if a.safe || strings.HasPrefix(content, aesGCMVersionPrefix) {
		return a.SafeDecrypt(content)
	}
	return a.DecryptLegacy(content)
}
